### PR TITLE
NEIG-35 Account Creation: Form Validation

### PR DESCRIPTION
**Pull request by sbinkader**
### Overview:
Implemented form validation of the sign up process. 

*Changes:*
* Reworked signUpForm.client.tsx to utilize Formik library while maintaining  most of the original codebase.
* New signUpValidation.ts that employs a yup validation schema

### CODE REVIEW

**Review by br-cz — CHANGES_REQUESTED** [review]
Looks like there's some conflict with the current changes to sign up but otherwise looks good to me. Feel free to either merge in the latest account creation PR or wait till its merged to main and pull it in here

**Review by br-cz — APPROVED** [review]
Just need to merge in current changes now but otherwise look good

**Comment by sbinkader** [comment]
> Just need to merge in current changes now but otherwise look good

I am working on that now have merged current changes from NEIG-34-2 that @alborzk worked on.

**Review by br-cz — APPROVED** [review]
Interesting, ive never seen formic before. Seems like a nice validation library. There's a couple leftover comments that would be nice if they were removed like ProfileSetup.tsx line 35-39, Signup.tsx line 25-31, etc but approved given comments removed

**Comment by sbinkader** [comment]
Yeah that was given our decision to use Yup for validation; Formik has nice integration with Yup (just 1 line to target schema).

**Pull request merged**
